export const ASSESSMENT_POLICY_VERSION = "1.0";
export const ASSESSMENT_POLICY_LAST_UPDATED_EN = "September 2026";
export const ASSESSMENT_POLICY_LAST_UPDATED_TH = "กันยายน 2569";

export const ASSESSMENT_POLICY_EN = [
["1. What the Assessment Is and Is Not","The SafeSpace Assessment is a wellbeing screening and reflection tool. It asks structured questions about mood, stress, daily wellbeing, relationships, school or home experiences, and other current wellbeing topics. It is not a medical diagnosis, treatment plan, professional evaluation, or test of your worth, personality, intelligence, character, or future."],
["2. Who It Is For, Voluntary Use, and Young Users","SafeSpace is designed with young people and general wellbeing in mind. Participation is voluntary. You may leave before submitting, pause, or stop if a question makes you uncomfortable. Younger users should take particular care with personal information and may involve a parent, guardian, teacher, school counselor, healthcare professional, or trusted adult when needed."],
["3. What the Assessment Asks","Questions may cover feelings and thoughts, stress, sleep or daily functioning, relationships, school or home experiences, and other wellbeing-related topics. The exact questions can change. Age may be requested to provide context. A broad nationality category may also be requested for analysis and presentation; it is not a request for an address, precise location, immigration documents, or identification number."],
["4. What You Should and Should Not Submit","Answer according to your experience, but provide only information necessary for the assessment. Do not submit passwords, account credentials, one-time codes, payment or banking details, government identification numbers, exact home addresses, private phone numbers, private social-media credentials, or another person's confidential information. If a question can be answered without identifying a person, prefer the non-identifying answer."],
["5. How Answers Are Processed — AI Analysis","After submission, SafeSpace sends assessment information to its analysis function. The documented flow may use OpenAI, Google Gemini as a configured fallback, and local fallback logic when remote AI is unavailable. AI may generate risk-related values, summaries, trends, factors, explanations, or general recommendations. AI can misunderstand language, context, sarcasm, cultural meaning, incomplete answers, or circumstances that were not provided. The output can be inaccurate, incomplete, generic, inconsistent, or unsuitable."],
["6. Sensitive Information, Consent, and Cross-Border Processing","Assessment answers can contain wellbeing-related personal information. Where required under PDPA, SafeSpace processes this sensitive data only after explicit consent through a separate, clear, unticked control. OpenAI and Google Gemini may process assessment information outside Thailand. SafeSpace relies on the providers' standard contractual safeguards."],
["7. Signed-In and Guest Assessment","When signed in, assessment records may be associated with the account and supported history features may show saved records. The application provides deletion of saved assessment records, but deletion through the interface should not be described as instantaneous removal from every backup, cache, log, or technical system unless verified. Guest assessment is also available. The frontend offers a guest option, but the current analyze-assessment Edge Function requires authentication and only saves signed-in assessments. Guest submission is therefore not confirmed to work or to be stored server-side in the current implementation. Guest server-side retention is not specified until the feature is implemented and verified. Guest mode is not a guarantee of complete anonymity. Assessment answers are not intended to become public Community posts."],
["8. Security, Data Minimisation, and Limits of Anonymity","Assessment requests can involve authentication, database access controls, Row Level Security, server-side validation, input validation, request limits, restricted private-record access, and controls around analysis requests. These measures reduce risk but cannot guarantee that errors, vulnerabilities, outages, or unauthorised access never occur. An online service cannot honestly promise complete anonymity merely because it does not ask for a name; account, session, technical, network, browser, and device information can sometimes make activity linkable."],
["9. Retention, Responsibilities, Contact, and Changes","Retention placeholders requiring developer confirmation: signed-in assessment records [until user deletes or account is deleted]; guest assessment information: no verified server-side retention period; the current analysis function requires authentication; related technical/security logs [1 day on the Supabase Free plan; confirm again if the project plan or provider settings change]. Do not promise immediate deletion from every backup, cache, log, or technical system unless verified. You are responsible for reviewing what you submit and for not submitting another person's information unless permitted. Privacy contact: safespacect@gmail.com. Version 1.0 — September 2026."],
["10. Emergency Support and Final Reminder","SafeSpace is not an emergency response service and cannot monitor your safety in real time. Thailand: 1669 — medical emergency; 1323 — Department of Mental Health hotline; 1300 — MSDHS social assistance line, especially for children and young people. Do not wait for an assessment, AI response, Community response, or administrator response when immediate real-world help is needed. You have the right to complain to the Thai Personal Data Protection Committee (PDPC) at pdpc.or.th if you believe your personal data has been mishandled. The assessment is one source of information for reflection, not a final judgment about you."]
];

export const ASSESSMENT_POLICY_TH = [
["1. แบบประเมินคืออะไรและไม่ใช่อะไร","แบบประเมิน SafeSpace เป็นเครื่องมือคัดกรองและสะท้อนสุขภาวะ ถามเกี่ยวกับอารมณ์ ความเครียด สุขภาวะประจำวัน ความสัมพันธ์ โรงเรียน บ้าน และหัวข้อสุขภาวะอื่น ๆ แบบประเมินไม่ใช่การวินิจฉัย การรักษา การประเมินโดยผู้เชี่ยวชาญ หรือการทดสอบคุณค่า บุคลิกภาพ ความฉลาด นิสัย หรืออนาคตของคุณ"],
["2. เหมาะกับใคร การใช้งานโดยสมัครใจ และผู้ใช้อายุน้อย","SafeSpace ออกแบบโดยคำนึงถึงเยาวชนและสุขภาวะทั่วไป การเข้าร่วมเป็นไปโดยสมัครใจ คุณสามารถออกก่อนส่ง พัก หรือหยุดได้หากคำถามทำให้ไม่สบายใจ ผู้ใช้อายุน้อยควรระมัดระวังข้อมูลส่วนตัวและอาจปรึกษาผู้ปกครอง ครู ที่ปรึกษา บุคลากรทางสุขภาพ หรือผู้ใหญ่ที่ไว้ใจได้เมื่อจำเป็น"],
["3. แบบประเมินถามอะไร","คำถามอาจเกี่ยวกับความรู้สึกและความคิด ความเครียด การนอนหรือการใช้ชีวิต ความสัมพันธ์ โรงเรียนหรือบ้าน และหัวข้อสุขภาวะอื่น ๆ ชุดคำถามอาจเปลี่ยนแปลงได้ อาจถามอายุเพื่อใช้เป็นบริบท และกลุ่มสัญชาติแบบกว้าง ๆ เพื่อการวิเคราะห์และการนำเสนอ ไม่ใช่การขอที่อยู่ ตำแหน่งละเอียด เอกสารตรวจคนเข้าเมือง หรือเลขประจำตัว"],
["4. สิ่งที่ควรและไม่ควรส่ง","ตอบตามประสบการณ์ของคุณแต่ให้ข้อมูลเท่าที่จำเป็น ห้ามส่งรหัสผ่าน ข้อมูลบัญชี รหัสครั้งเดียว ข้อมูลการเงิน เลขประจำตัวรัฐ ที่อยู่ละเอียด เบอร์ส่วนตัว ข้อมูลรับรองโซเชียลส่วนตัว หรือข้อมูลลับของผู้อื่น หากตอบได้โดยไม่ระบุตัวบุคคล ให้เลือกคำตอบที่ไม่ระบุตัวตน"],
["5. การประมวลผลคำตอบด้วย AI","หลังส่งคำตอบ SafeSpace ส่งข้อมูลไปยังฟังก์ชันวิเคราะห์ flow ที่บันทึกไว้สามารถใช้ OpenAI, Google Gemini เป็นตัวสำรอง และ logic สำรองภายในเมื่อ AI ภายนอกใช้ไม่ได้ AI อาจสร้างค่าความเสี่ยง สรุป แนวโน้ม ปัจจัย คำอธิบาย หรือคำแนะนำทั่วไป และอาจเข้าใจภาษา บริบท การประชด ความหมายทางวัฒนธรรม คำตอบไม่ครบ หรือสถานการณ์ที่ไม่ได้ให้ข้อมูลผิดพลาดได้ ผลลัพธ์จึงอาจไม่ถูกต้อง ไม่ครบ กว้างเกินไป ไม่สม่ำเสมอ หรือไม่เหมาะกับบุคคล"],
["6. ข้อมูลละเอียดอ่อน ความยินยอม และการประมวลผลข้ามประเทศ","คำตอบแบบประเมินอาจมีข้อมูลสุขภาวะส่วนบุคคลที่ละเอียดอ่อน เมื่อกฎหมาย PDPA กำหนด SafeSpace ต้องประมวลผลข้อมูลดังกล่าวหลังได้รับความยินยอมโดยชัดแจ้งผ่านช่องยินยอมแยกที่ชัดเจนและไม่เลือกไว้ล่วงหน้า OpenAI และ Google Gemini อาจประมวลผลข้อมูลนอกประเทศไทย โดย SafeSpace อาศัยมาตรการคุ้มครองตามสัญญามาตรฐานของผู้ให้บริการ"],
["7. แบบประเมินสำหรับผู้เข้าสู่ระบบและ Guest","เมื่อเข้าสู่ระบบ ข้อมูลแบบประเมินอาจเชื่อมกับบัญชีและประวัติที่รองรับอาจแสดงผลที่บันทึกไว้ แอปมีการลบประวัติแบบประเมินที่บันทึก แต่ไม่ควรกล่าวว่าลบจาก backup, cache, log หรือระบบเทคนิคทุกแห่งทันทีหากยังไม่ตรวจสอบ Guest assessment ก็มีได้ หน้าเว็บมีตัวเลือก Guest แต่ Edge Function analyze-assessment ปัจจุบันกำหนดให้ต้องเข้าสู่ระบบและบันทึกเฉพาะแบบประเมินของผู้ที่เข้าสู่ระบบ จึงยังยืนยันไม่ได้ว่าการส่งแบบประเมิน Guest ทำงานหรือถูกเก็บบนเซิร์ฟเวอร์ในระบบปัจจุบัน ระยะเวลาเก็บข้อมูล Guest ยังไม่ระบุจนกว่าจะพัฒนาและตรวจสอบฟีเจอร์นี้ Guest ไม่ใช่การรับประกันว่าจะไม่สามารถเชื่อมโยงตัวตนได้ ข้อมูลแบบประเมินไม่ตั้งใจให้กลายเป็นโพสต์ชุมชนสาธารณะ"],
["8. ความปลอดภัย การลดข้อมูล และข้อจำกัดของการไม่เปิดเผยตัวตน","คำขอแบบประเมินอาจเกี่ยวข้องกับการยืนยันตัวตน สิทธิฐานข้อมูล RLS การตรวจสอบฝั่งเซิร์ฟเวอร์และอินพุต การจำกัดคำขอ การจำกัดการเข้าถึงข้อมูลส่วนตัว และการควบคุมการวิเคราะห์ มาตรการเหล่านี้ลดความเสี่ยงแต่ไม่รับประกันว่าจะไม่มีข้อผิดพลาด ช่องโหว่ ระบบล่ม หรือการเข้าถึงโดยไม่ได้รับอนุญาต บริการออนไลน์ไม่ควรรับประกันว่าไม่เปิดเผยตัวตนอย่างสมบูรณ์เพียงเพราะไม่ถามชื่อ เพราะข้อมูลบัญชี เซสชัน เทคนิค เครือข่าย เบราว์เซอร์ และอุปกรณ์อาจเชื่อมโยงกิจกรรมกลับมาหาบุคคลได้"],
["9. การเก็บรักษา ความรับผิดชอบ การติดต่อ และการเปลี่ยนแปลง","ระยะเวลาที่ต้องยืนยัน: ประวัติแบบประเมิน [จนกว่าผู้ใช้จะลบหรือบัญชีถูกลบ]; ข้อมูล Guest: ยังไม่มีระยะเวลาเก็บบนเซิร์ฟเวอร์ที่ยืนยันได้ เนื่องจากฟังก์ชันวิเคราะห์ปัจจุบันต้องเข้าสู่ระบบ; log ทางเทคนิค/ความปลอดภัย [1 วันสำหรับ Supabase Free plan; โปรดตรวจสอบอีกครั้งหากเปลี่ยนแพ็กเกจหรือการตั้งค่าผู้ให้บริการ] ไม่ควรรับประกันการลบจาก backup, cache, log หรือระบบเทคนิคทุกแห่งทันที คุณมีหน้าที่ตรวจสอบสิ่งที่ส่งและไม่ส่งข้อมูลของผู้อื่นหากไม่มีสิทธิ ติดต่อความเป็นส่วนตัว: safespacect@gmail.com Version 1.0 — กันยายน 2569"],
["10. ความช่วยเหลือฉุกเฉินและข้อเตือนสุดท้าย","SafeSpace ไม่ใช่บริการตอบสนองเหตุฉุกเฉินและไม่สามารถติดตามความปลอดภัยแบบเรียลไทม์ ประเทศไทย: 1669 — เหตุฉุกเฉินทางการแพทย์; 1323 — สายด่วนสุขภาพจิต กรมสุขภาพจิต; 1300 — สายด่วนช่วยเหลือสังคม พม. โดยเฉพาะเด็กและเยาวชน อย่ารอผลแบบประเมิน AI การตอบจากชุมชน หรือผู้ดูแลเมื่อจำเป็นต้องได้รับความช่วยเหลือทันที คุณมีสิทธิร้องเรียนต่อสำนักงานคณะกรรมการคุ้มครองข้อมูลส่วนบุคคล (PDPC) ที่ pdpc.or.th หากเชื่อว่าข้อมูลส่วนบุคคลถูกจัดการอย่างไม่เหมาะสม แบบประเมินเป็นข้อมูลหนึ่งเพื่อการสะท้อน ไม่ใช่คำตัดสินสุดท้ายเกี่ยวกับคุณ"]
];