export const ASSESSMENT_POLICY_VERSION = "2.0";
export const ASSESSMENT_POLICY_LAST_UPDATED_EN = "29 September 2026";
export const ASSESSMENT_POLICY_LAST_UPDATED_TH = "29 กันยายน 2569";

export const ASSESSMENT_POLICY_EN = [
  ["1. What is the SafeSpace Assessment?",
    "The SafeSpace Assessment is a wellbeing screening and reflection tool. It asks structured questions about experiences that may relate to mood, stress, everyday wellbeing, relationships, school or home experiences, and other areas included in the current assessment. The purpose is to help you reflect on your answers and provide general information that may be useful to you. It is not a test of your worth, personality, intelligence, character, or future."],
  ["2. Who is the assessment for?",
    "SafeSpace is designed with young people and general wellbeing in mind. You should only continue if you understand that this is an informational tool rather than a medical service. If you are unsure whether using an online wellbeing tool is appropriate for you, consider talking with a parent, guardian, teacher, school counselor, healthcare professional, or another trusted adult."],
  ["3. Participation is voluntary",
    "You choose whether to use the assessment. You may leave before submitting your answers, and you should not feel pressured to continue because you have already started. If a question makes you uncomfortable, you may pause or stop. Agreeing to this policy does not mean that you must answer every future question outside the assessment either."],
  ["4. What questions may ask about",
    "Questions can cover feelings, thoughts, stress, sleep or daily functioning, relationships, school or home experiences, and other wellbeing-related topics. The exact questions can change as the project develops. The assessment is designed to collect responses to its displayed questions; it is not a request for a full personal history."],
  ["5. Answer honestly, but share only what is necessary",
    "Choose the answer that best represents your experience for the period or situation described by the question. You do not need to add extra personal details to explain an answer. Do not put passwords, account credentials, payment information, identification numbers, exact addresses, private contact details, or another person's private information into assessment responses."],
  ["6. Why does SafeSpace ask for age?",
    "Age is requested because experiences and wellbeing needs can differ across age groups. It provides context for the assessment and may be used with the submitted answers when the analysis is generated. Age is not intended to determine your value or to label you as a person. You should enter your age accurately enough for the assessment to use the appropriate context."],
  ["7. Why may SafeSpace ask for nationality?",
    "The current assessment can request a broad nationality category to provide additional context for analysis and presentation. It is not a request for your home address, precise location, immigration documents, identification number, or other unnecessary identifying information. If a field does not apply to you, use the option provided by the interface rather than entering unrelated personal information."],
  ["8. What information is submitted?",
    "When you submit the assessment, the application can send the assessment answers together with the information needed for the assessment, such as language, age, and nationality. Depending on whether you are signed in, the request may also be associated with account/session information needed to provide the feature. Do not assume that a text field is anonymous simply because it does not ask for your name."],
  ["9. How are answers processed?",
    "After submission, SafeSpace sends the assessment information to its analysis function so that a result can be generated. The application may use automated or AI-assisted analysis to interpret the answers and produce information such as a risk level, summary, trends, factors, or general recommendations. Automated analysis can misunderstand language, context, sarcasm, cultural differences, or an individual's circumstances. Its output must therefore be treated as an estimate or screening result, not as a definitive statement about you."],
  ["10. AI limitations and human judgment",
    "AI can produce answers that are incomplete, inaccurate, overly general, or inappropriate for a particular person. The system does not know everything about your life and cannot directly observe your circumstances. A generated result should not override your own understanding of your experience or the advice of an appropriately qualified professional. If the result seems wrong, confusing, or inconsistent with what you are experiencing, you do not have to accept it as true."],
  ["11. This is not a medical diagnosis",
    "The SafeSpace Assessment is not a diagnostic examination and does not establish that you have depression, anxiety, another mental health condition, or any other medical condition. A score, risk level, label, or AI explanation from SafeSpace should not be presented to another person as a professional diagnosis. Diagnosis and treatment decisions require appropriate professional assessment and context."],
  ["12. What does a result mean?",
    "A result is an interpretation of the information provided through the assessment. It can indicate areas that may deserve attention, but it cannot measure every part of your wellbeing and cannot predict your future. A lower or higher result does not make someone better or worse than another person. The result should be used as one piece of information for reflection, not as a permanent label."],
  ["13. If the result does not feel accurate",
    "Your experience is more than a number or automated summary. If a result does not match how you feel, consider the possibility that the tool has limitations or that the questions did not capture your situation. You can discuss what you are experiencing with someone you trust or with a qualified professional. You do not need to change your understanding of yourself just to match an automated result."],
  ["14. If the assessment brings up difficult feelings",
    "Some wellbeing questions may make you think about experiences that are difficult, stressful, or upsetting. You may pause or stop if you need to. Consider moving to a comfortable place and talking with a trusted person if you need support. SafeSpace is not a substitute for real-world support from people who can understand your circumstances and respond directly."],
  ["15. If you need urgent or emergency help",
    "SafeSpace is not an emergency response service and cannot monitor your safety in real time. If you or another person is in immediate danger or needs urgent medical assistance, do not wait for an assessment result. Contact an appropriate emergency service, healthcare service, trusted adult, or other local source of immediate help. In Thailand, the Department of Mental Health hotline is 1323; emergency services may also be appropriate depending on the situation."],
  ["16. Extra care for younger users",
    "SafeSpace may be used by teenagers and other young people. Younger users should take particular care not to disclose unnecessary identifying information online. If you are unsure about a question, privacy, or what to do after receiving a result, consider involving a parent, guardian, teacher, school counselor, healthcare professional, or another trusted adult."],
  ["17. Signed-in assessment data",
    "If you are signed in, assessment information can be associated with your account so that account-related features can work, including access to relevant assessment records where supported by the application. Signed-in assessment information is intended to be separate from public community posts. You should still avoid entering unnecessary personal information because account association does not make unnecessary disclosure safe."],
  ["18. Guest assessment",
    "SafeSpace can allow an assessment to be completed as a guest. Guest results are handled differently from signed-in account records and can be returned through the current guest/session experience. Guest mode should not be understood as a guarantee of complete anonymity: browsers, devices, networks, and technical services can retain or process information outside the visible assessment screen. Do not use guest mode as a reason to submit sensitive identifying information."],
  ["19. Is the assessment public?",
    "Your assessment answers are not intended to become a public community post, public comment, or public profile simply because you complete the assessment. Assessment and community features are separate parts of SafeSpace. If you later choose to share a result or describe your experience publicly, you are responsible for deciding what personal information you are comfortable disclosing."],
  ["20. Who may technically process information?",
    "Operating an online assessment requires technical services to receive, store, transmit, authenticate, or process information. Depending on the feature and implementation, this can include the SafeSpace application, database or storage infrastructure, authentication services, hosting infrastructure, and the service used to perform the assessment analysis. The exact technical providers and configurations can change as the project develops. SafeSpace should not claim that online processing is completely risk-free."],
  ["21. How SafeSpace approaches security",
    "SafeSpace uses technical controls intended to reduce unauthorized access and misuse. Depending on the feature, these can include authentication, database access controls, row-level security, server-side validation, input validation, request limits, restricted access to private records, and controls around analysis requests. Security measures reduce risk but cannot guarantee that a system will never experience an error, vulnerability, outage, or unauthorized access."],
  ["22. Data minimization: what you should not submit",
    "Only provide information that is reasonably necessary for the assessment. Do not submit passwords, one-time codes, payment or banking details, government identification numbers, exact home addresses, private phone numbers, private social-media credentials, or another person's confidential information. If a question can be answered without identifying a person, prefer the non-identifying answer."],
  ["23. Privacy is not the same as complete anonymity",
    "An online service cannot honestly promise that a user is completely anonymous simply because the interface does not ask for a name. Account information, technical information, session information, network information, and combinations of details can sometimes make activity linkable to a person. SafeSpace therefore asks users to avoid unnecessary identifying information rather than relying on a promise of anonymity."],
  ["24. Use of assessment information",
    "Assessment information is collected in order to provide the assessment and related application functionality. It should not be treated as a public social-media post. Any additional use of assessment information should be consistent with the information presented to users and the actual implementation of the project. If the project materially changes how assessment information is used, this policy should be reviewed and updated."],
  ["25. Advertising and sale of assessment information",
    "The assessment is not presented as a feature for selling your private wellbeing answers to other users. Your assessment responses should not be treated as ordinary public content. SafeSpace should only describe data uses that are actually supported by the project. If future features introduce a materially different use of wellbeing information, users should receive updated information before relying on the changed behavior."],
  ["26. Retention and deletion",
    "How long information remains available depends on how the assessment is used and how the application's current storage is configured. Signed-in records may remain associated with an account where the application provides that functionality. Guest results are intended to remain within the guest/session flow rather than becoming a normal account record. SafeSpace should not promise immediate deletion from every backup, log, cache, or technical system unless the project actually provides and verifies that guarantee."],
  ["27. Your responsibility when using the assessment",
    "You are responsible for reviewing what you submit before pressing the final submission button. Do not submit information about another person unless it is genuinely necessary and you are permitted to share it. Do not use the assessment to test, harass, impersonate, or deliberately mislead the system. Using random or deliberately false answers can make the generated result less meaningful."],
  ["28. Accuracy and technical problems",
    "The assessment may be affected by software bugs, network failures, service outages, changes to the question set, language differences, or problems in automated analysis. A result may also be affected if answers are incomplete or intentionally inaccurate. If the application reports an error, do not repeatedly submit the same sensitive information just to make the request work; instead, try again later or use an appropriate support channel."],
  ["29. Changes to the assessment",
    "SafeSpace is a school project that may continue to change. Questions, scoring or analysis methods, interface behavior, technical services, security controls, and privacy practices may be updated. A future version may therefore behave differently from an earlier version. The policy version and update date are shown so users can identify the version they are accepting."],
  ["30. Policy acceptance",
    "Before the assessment begins, you must have an opportunity to review this policy. The acceptance control is intentionally disabled until you reach the end of the policy. By selecting “Agree & Accept”, you confirm that you have had an opportunity to read the policy, understand that the assessment is voluntary, understand that your answers may be processed by automated or AI-assisted systems, understand that the result is not a diagnosis, understand the importance of avoiding unnecessary personal information, and choose to continue. If you do not agree, you can leave without starting the assessment."],
  ["31. Contact and feedback",
    "If you find a privacy, safety, security, accessibility, or assessment problem, use the contact or support route provided by SafeSpace where available. When reporting a technical problem, do not include passwords or unnecessary sensitive information in the report. A clear description of what happened, without private details, is usually safer than sending the entire assessment response."],
  ["32. Important reminder before you continue",
    "Take the assessment only when you are comfortable doing so. Answer the questions based on your own experience, share only what is necessary, and remember that a computer-generated result cannot fully understand a person. SafeSpace is intended to support reflection and awareness, not to replace trusted people, professional care, or emergency services."]
];

export const ASSESSMENT_POLICY_TH = [
  ["1. แบบประเมินของ SafeSpace คืออะไร",
    "แบบประเมินของ SafeSpace เป็นเครื่องมือสำหรับการคัดกรองและสะท้อนสุขภาวะเบื้องต้น โดยใช้คำถามที่เป็นโครงสร้างเกี่ยวกับประสบการณ์ที่อาจเกี่ยวข้องกับอารมณ์ ความเครียด สุขภาวะในชีวิตประจำวัน ความสัมพันธ์ ประสบการณ์ที่โรงเรียนหรือที่บ้าน และหัวข้ออื่นตามแบบประเมินในปัจจุบัน จุดประสงค์คือช่วยให้คุณทบทวนคำตอบและได้รับข้อมูลทั่วไปที่อาจเป็นประโยชน์ ไม่ใช่การทดสอบคุณค่า บุคลิกภาพ ความฉลาด ลักษณะนิสัย หรืออนาคตของคุณ"],
  ["2. แบบประเมินนี้เหมาะกับใคร",
    "SafeSpace ออกแบบโดยคำนึงถึงวัยรุ่นและสุขภาวะทั่วไปเป็นสำคัญ คุณควรทำต่อเมื่อเข้าใจว่านี่เป็นเครื่องมือให้ข้อมูล ไม่ใช่บริการทางการแพทย์ หากไม่แน่ใจว่าการใช้เครื่องมือด้านสุขภาวะออนไลน์เหมาะกับคุณหรือไม่ ควรพิจารณาพูดคุยกับพ่อแม่ ผู้ปกครอง ครู ที่ปรึกษาโรงเรียน บุคลากรทางสุขภาพ หรือผู้ใหญ่ที่คุณไว้ใจ"],
  ["3. การเข้าร่วมเป็นไปโดยสมัครใจ",
    "คุณเป็นผู้ตัดสินใจว่าจะใช้แบบประเมินหรือไม่ คุณสามารถออกจากแบบประเมินก่อนส่งคำตอบ และไม่ควรรู้สึกว่าต้องทำต่อเพียงเพราะเริ่มไปแล้ว หากคำถามทำให้ไม่สบายใจ คุณสามารถหยุดหรือพักได้ การยอมรับนโยบายนี้ไม่ได้หมายความว่าคุณต้องตอบคำถามอื่นใดนอกเหนือจากแบบประเมินในอนาคต"],
  ["4. คำถามอาจเกี่ยวกับเรื่องใดบ้าง",
    "คำถามอาจเกี่ยวกับความรู้สึก ความคิด ความเครียด การนอนหรือการใช้ชีวิตประจำวัน ความสัมพันธ์ ประสบการณ์ที่โรงเรียนหรือที่บ้าน และหัวข้อด้านสุขภาวะอื่น ๆ ชุดคำถามที่แสดงอาจเปลี่ยนแปลงได้เมื่อโครงการพัฒนา แบบประเมินมีไว้เพื่อรับคำตอบต่อคำถามที่แสดง ไม่ได้ขอประวัติชีวิตทั้งหมดของคุณ"],
  ["5. ตอบตามประสบการณ์จริง แต่ให้ข้อมูลเท่าที่จำเป็น",
    "เลือกคำตอบที่ตรงกับประสบการณ์ของคุณมากที่สุดตามช่วงเวลาหรือสถานการณ์ที่คำถามกล่าวถึง คุณไม่จำเป็นต้องเพิ่มรายละเอียดส่วนตัวเพื่ออธิบายคำตอบ ห้ามใส่รหัสผ่าน ข้อมูลเข้าสู่ระบบ ข้อมูลการชำระเงิน เลขประจำตัว ที่อยู่แบบละเอียด ข้อมูลติดต่อส่วนตัว หรือข้อมูลส่วนตัวของผู้อื่นลงในคำตอบ"],
  ["6. ทำไม SafeSpace จึงถามอายุ",
    "เราขออายุเพราะประสบการณ์และความต้องการด้านสุขภาวะอาจแตกต่างกันตามช่วงวัย อายุช่วยให้ระบบมีบริบทในการประเมินและอาจถูกใช้ร่วมกับคำตอบเพื่อสร้างผลลัพธ์ อายุไม่ได้มีไว้เพื่อกำหนดคุณค่าหรือติดป้ายว่าคุณเป็นคนแบบใด ควรกรอกอายุให้ถูกต้องเพียงพอสำหรับการใช้บริบทที่เหมาะสม"],
  ["7. ทำไม SafeSpace จึงอาจถามสัญชาติ",
    "แบบประเมินปัจจุบันสามารถขอข้อมูลสัญชาติในรูปแบบกว้าง ๆ เพื่อเพิ่มบริบทในการวิเคราะห์และการนำเสนอข้อมูล ไม่ใช่การขอที่อยู่ ตำแหน่งที่แน่นอน เอกสารตรวจคนเข้าเมือง เลขประจำตัว หรือข้อมูลระบุตัวตนอื่นที่ไม่จำเป็น หากช่องข้อมูลไม่ตรงกับคุณ ให้ใช้ตัวเลือกที่ระบบมีแทนการกรอกข้อมูลส่วนตัวอื่น"],
  ["8. ข้อมูลอะไรถูกส่งเมื่อส่งแบบประเมิน",
    "เมื่อคุณส่งแบบประเมิน แอปสามารถส่งคำตอบพร้อมข้อมูลที่จำเป็นต่อการประเมิน เช่น ภาษา อายุ และสัญชาติ ขึ้นอยู่กับว่าคุณเข้าสู่ระบบหรือไม่ คำขออาจเชื่อมโยงกับข้อมูลบัญชีหรือเซสชันที่จำเป็นต่อการให้บริการ อย่าคิดว่าช่องข้อความเป็นนิรนามเพียงเพราะช่องนั้นไม่ได้ถามชื่อ"],
  ["9. คำตอบถูกประมวลผลอย่างไร",
    "หลังจากส่งคำตอบ SafeSpace จะส่งข้อมูลแบบประเมินไปยังฟังก์ชันวิเคราะห์เพื่อสร้างผลลัพธ์ ระบบอาจใช้การประมวลผลอัตโนมัติหรือ AI เพื่อวิเคราะห์คำตอบและสร้างข้อมูล เช่น ระดับความเสี่ยง สรุป แนวโน้ม ปัจจัย หรือคำแนะนำทั่วไป การวิเคราะห์อัตโนมัติอาจเข้าใจภาษา บริบท การประชด ความแตกต่างทางวัฒนธรรม หรือสถานการณ์เฉพาะบุคคลผิดได้ ดังนั้นผลลัพธ์ควรถูกมองว่าเป็นผลคัดกรองหรือการประมาณ ไม่ใช่ข้อสรุปที่แน่นอนเกี่ยวกับตัวคุณ"],
  ["10. ข้อจำกัดของ AI และความสำคัญของการใช้วิจารณญาณ",
    "AI อาจสร้างคำตอบที่ไม่ครบถ้วน ไม่ถูกต้อง กว้างเกินไป หรือไม่เหมาะกับบุคคลใดบุคคลหนึ่ง ระบบไม่รู้ทุกอย่างเกี่ยวกับชีวิตของคุณและไม่สามารถสังเกตสถานการณ์จริงของคุณได้โดยตรง ผลลัพธ์ที่สร้างขึ้นไม่ควรมีอำนาจเหนือความเข้าใจของคุณเองหรือคำแนะนำจากผู้เชี่ยวชาญที่มีคุณสมบัติเหมาะสม หากผลไม่ถูกต้อง สับสน หรือไม่ตรงกับสิ่งที่คุณกำลังเผชิญ คุณไม่จำเป็นต้องเชื่อว่าเป็นความจริงเพียงเพราะระบบสร้างผลนั้นขึ้นมา"],
  ["11. แบบประเมินนี้ไม่ใช่การวินิจฉัยโรค",
    "แบบประเมิน SafeSpace ไม่ใช่การตรวจวินิจฉัยและไม่สามารถยืนยันว่าคุณเป็นโรคซึมเศร้า ภาวะวิตกกังวล ภาวะทางสุขภาพจิตอื่น หรือโรคทางการแพทย์ใด ๆ คะแนน ระดับความเสี่ยง ป้ายกำกับ หรือคำอธิบายจาก AI ไม่ควรถูกนำเสนอแก่ผู้อื่นว่าเป็นการวินิจฉัยจากผู้เชี่ยวชาญ การวินิจฉัยและการตัดสินใจเรื่องการรักษาต้องอาศัยการประเมินที่เหมาะสมและบริบทจากผู้เชี่ยวชาญ"],
  ["12. ผลการประเมินหมายความว่าอย่างไร",
    "ผลลัพธ์เป็นการตีความข้อมูลที่คุณให้ผ่านแบบประเมิน อาจชี้ให้เห็นบางด้านที่ควรใส่ใจ แต่ไม่สามารถวัดสุขภาวะของคุณได้ทุกด้านและไม่สามารถทำนายอนาคตได้ ผลที่ต่ำหรือสูงกว่าไม่ได้ทำให้ใครดีกว่าหรือแย่กว่าอีกคน และผลลัพธ์ไม่ควรถูกใช้เป็นป้ายกำกับถาวรของตัวคุณ"],
  ["13. หากผลลัพธ์ไม่ตรงกับความรู้สึกของคุณ",
    "ประสบการณ์ของคุณมีมากกว่าตัวเลขหรือสรุปจากระบบอัตโนมัติ หากผลไม่ตรงกับความรู้สึกของคุณ ให้พิจารณาว่าเครื่องมืออาจมีข้อจำกัดหรือคำถามอาจไม่ครอบคลุมสถานการณ์ของคุณ คุณสามารถพูดคุยกับคนที่ไว้ใจหรือผู้เชี่ยวชาญที่เหมาะสมเกี่ยวกับสิ่งที่คุณกำลังเผชิญ ไม่จำเป็นต้องเปลี่ยนความเข้าใจต่อตัวเองเพียงเพื่อให้ตรงกับผลจากระบบ"],
  ["14. หากแบบประเมินทำให้เกิดความรู้สึกที่ยากลำบาก",
    "คำถามด้านสุขภาวะบางข้ออาจทำให้คุณนึกถึงประสบการณ์ที่ยาก เครียด หรือไม่สบายใจ คุณสามารถหยุดหรือออกจากแบบประเมินได้ หากต้องการความช่วยเหลือ ลองอยู่ในสถานที่ที่รู้สึกปลอดภัยและพูดคุยกับคนที่ไว้ใจ SafeSpace ไม่สามารถทดแทนการสนับสนุนจากคนจริงที่เข้าใจสถานการณ์ของคุณและสามารถตอบสนองได้โดยตรง"],
  ["15. หากต้องการความช่วยเหลือเร่งด่วนหรือฉุกเฉิน",
    "SafeSpace ไม่ใช่บริการตอบสนองเหตุฉุกเฉินและไม่สามารถเฝ้าดูความปลอดภัยของคุณแบบเรียลไทม์ หากคุณหรือผู้อื่นอยู่ในอันตรายทันทีหรือต้องการความช่วยเหลือทางการแพทย์เร่งด่วน อย่ารอผลแบบประเมิน ให้ติดต่อหน่วยฉุกเฉิน บริการสุขภาพ ผู้ใหญ่ที่ไว้ใจ หรือแหล่งช่วยเหลือในพื้นที่ที่เหมาะสม ในประเทศไทยสามารถติดต่อสายด่วนสุขภาพจิต กรมสุขภาพจิต 1323 และในสถานการณ์ฉุกเฉินอาจต้องติดต่อบริการฉุกเฉินที่เหมาะสม"],
  ["16. การดูแลเพิ่มเติมสำหรับผู้ใช้อายุน้อย",
    "SafeSpace อาจถูกใช้โดยวัยรุ่นและเยาวชน ผู้ใช้อายุน้อยควรระมัดระวังเป็นพิเศษไม่เปิดเผยข้อมูลที่สามารถระบุตัวตนโดยไม่จำเป็นทางออนไลน์ หากไม่แน่ใจเกี่ยวกับคำถาม ความเป็นส่วนตัว หรือควรทำอย่างไรหลังได้รับผลลัพธ์ ควรพิจารณาพูดคุยกับพ่อแม่ ผู้ปกครอง ครู ที่ปรึกษาโรงเรียน บุคลากรทางสุขภาพ หรือผู้ใหญ่ที่ไว้ใจ"],
  ["17. ข้อมูลแบบประเมินเมื่อเข้าสู่ระบบ",
    "หากคุณเข้าสู่ระบบ ข้อมูลแบบประเมินสามารถเชื่อมโยงกับบัญชีเพื่อให้ฟีเจอร์ของบัญชีทำงานได้ รวมถึงการเข้าถึงข้อมูลการประเมินที่แอปรองรับ ข้อมูลแบบประเมินที่เข้าสู่ระบบมีจุดประสงค์ให้แยกจากโพสต์สาธารณะในชุมชน อย่างไรก็ตาม การเชื่อมโยงกับบัญชีไม่ได้ทำให้การเปิดเผยข้อมูลส่วนตัวที่ไม่จำเป็นปลอดภัย จึงควรให้ข้อมูลเท่าที่จำเป็น"],
  ["18. การทำแบบประเมินแบบผู้เยี่ยมชม",
    "SafeSpace สามารถเปิดให้ทำแบบประเมินแบบผู้เยี่ยมชมได้ ผลของผู้เยี่ยมชมถูกจัดการแตกต่างจากระเบียนบัญชีและสามารถส่งกลับผ่านประสบการณ์ของผู้เยี่ยมชม/เซสชัน โหมดผู้เยี่ยมชมไม่ควรถูกเข้าใจว่าเป็นการรับประกันความไม่ระบุตัวตนอย่างสมบูรณ์ เพราะเบราว์เซอร์ อุปกรณ์ เครือข่าย และบริการทางเทคนิคอาจเก็บหรือประมวลผลข้อมูลนอกหน้าจอแบบประเมิน อย่าใช้โหมดผู้เยี่ยมชมเป็นเหตุผลในการส่งข้อมูลระบุตัวตนที่ละเอียดอ่อน"],
  ["19. แบบประเมินเป็นข้อมูลสาธารณะหรือไม่",
    "คำตอบแบบประเมินไม่ได้มีจุดประสงค์ให้กลายเป็นโพสต์ ความคิดเห็น หรือโปรไฟล์สาธารณะเพียงเพราะคุณทำแบบประเมินเสร็จ แบบประเมินและชุมชนเป็นฟีเจอร์คนละส่วน หากคุณเลือกแชร์ผลหรือเล่าประสบการณ์ต่อสาธารณะภายหลัง คุณควรตัดสินใจด้วยตัวเองว่าข้อมูลส่วนตัวใดที่ยอมเปิดเผย"],
  ["20. ใครอาจประมวลผลข้อมูลในทางเทคนิค",
    "การให้บริการแบบประเมินออนไลน์จำเป็นต้องมีบริการทางเทคนิคสำหรับรับ ส่ง จัดเก็บ ยืนยันตัวตน หรือประมวลผลข้อมูล ขึ้นอยู่กับฟีเจอร์และการติดตั้งจริง อาจรวมถึงแอป SafeSpace โครงสร้างพื้นฐานฐานข้อมูลหรือพื้นที่จัดเก็บ ระบบยืนยันตัวตน โฮสติ้ง และบริการที่ใช้วิเคราะห์แบบประเมิน ผู้ให้บริการและการตั้งค่าทางเทคนิคอาจเปลี่ยนแปลงได้เมื่อโครงการพัฒนา SafeSpace ไม่ควรอ้างว่าการประมวลผลออนไลน์ไม่มีความเสี่ยงเลย"],
  ["21. SafeSpace ดูแลความปลอดภัยของข้อมูลอย่างไร",
    "SafeSpace ใช้มาตรการทางเทคนิคเพื่อลดการเข้าถึงโดยไม่ได้รับอนุญาตและการใช้งานที่ไม่เหมาะสม โดยขึ้นอยู่กับฟีเจอร์ เช่น การยืนยันตัวตน การควบคุมการเข้าถึงฐานข้อมูล Row-level security การตรวจสอบฝั่งเซิร์ฟเวอร์ การตรวจสอบข้อมูล การจำกัดคำขอ การจำกัดการเข้าถึงระเบียนส่วนตัว และการควบคุมคำขอที่เกี่ยวข้องกับการวิเคราะห์ มาตรการเหล่านี้ช่วยลดความเสี่ยง แต่ไม่สามารถรับประกันได้ว่าระบบจะไม่มีข้อผิดพลาด ช่องโหว่ การหยุดให้บริการ หรือการเข้าถึงโดยไม่ได้รับอนุญาต"],
  ["22. การลดการเก็บข้อมูล: สิ่งที่ไม่ควรส่ง",
    "ควรให้เฉพาะข้อมูลที่จำเป็นต่อแบบประเมินอย่างสมเหตุสมผล ห้ามส่งรหัสผ่าน รหัสใช้ครั้งเดียว ข้อมูลธนาคารหรือการชำระเงิน เลขประจำตัวของรัฐ ที่อยู่บ้านแบบละเอียด เบอร์โทรศัพท์ส่วนตัว ข้อมูลเข้าสู่ระบบโซเชียลมีเดีย หรือข้อมูลลับของผู้อื่น หากสามารถตอบคำถามได้โดยไม่ระบุตัวบุคคล ควรเลือกคำตอบที่ไม่เปิดเผยข้อมูลดังกล่าว"],
  ["23. ความเป็นส่วนตัวไม่เท่ากับการไม่เปิดเผยตัวตนโดยสมบูรณ์",
    "บริการออนไลน์ไม่สามารถรับประกันอย่างซื่อสัตย์ว่าผู้ใช้เป็นนิรนามโดยสมบูรณ์เพียงเพราะหน้าจอไม่ได้ถามชื่อ ข้อมูลบัญชี ข้อมูลทางเทคนิค ข้อมูลเซสชัน ข้อมูลเครือข่าย และการรวมรายละเอียดหลายอย่างอาจทำให้กิจกรรมเชื่อมโยงกับบุคคลได้ ด้วยเหตุนี้ SafeSpace จึงขอให้ผู้ใช้หลีกเลี่ยงข้อมูลระบุตัวตนที่ไม่จำเป็น แทนการพึ่งพาคำรับรองว่าเป็นนิรนาม"],
  ["24. การใช้ข้อมูลแบบประเมิน",
    "ข้อมูลแบบประเมินถูกเก็บเพื่อให้บริการแบบประเมินและฟังก์ชันที่เกี่ยวข้องของแอป ไม่ควรถูกถือเป็นเนื้อหาสาธารณะทั่วไป การใช้ข้อมูลเพิ่มเติมควรสอดคล้องกับข้อมูลที่อธิบายแก่ผู้ใช้และการทำงานจริงของโครงการ หากโครงการเปลี่ยนแปลงการใช้ข้อมูลแบบประเมินอย่างมีนัยสำคัญ ควรทบทวนและปรับปรุงนโยบายนี้"],
  ["25. โฆษณาและการขายข้อมูลแบบประเมิน",
    "แบบประเมินไม่ได้ถูกนำเสนอว่าเป็นฟีเจอร์สำหรับขายคำตอบด้านสุขภาวะส่วนตัวของคุณให้ผู้ใช้อื่น คำตอบแบบประเมินไม่ควรถูกถือเป็นเนื้อหาสาธารณะทั่วไป SafeSpace ควรอธิบายเฉพาะการใช้ข้อมูลที่โครงการรองรับจริง หากในอนาคตมีการใช้ข้อมูลด้านสุขภาวะในรูปแบบที่แตกต่างอย่างมีนัยสำคัญ ควรให้ข้อมูลที่อัปเดตแก่ผู้ใช้ก่อนที่จะคาดหวังให้ผู้ใช้พึ่งพาพฤติกรรมใหม่"],
  ["26. การเก็บรักษาและการลบข้อมูล",
    "ระยะเวลาที่ข้อมูลยังเข้าถึงได้ขึ้นอยู่กับวิธีใช้แบบประเมินและการตั้งค่าการจัดเก็บข้อมูลของแอปในปัจจุบัน สำหรับผู้ที่เข้าสู่ระบบ ระเบียนอาจยังเชื่อมกับบัญชีตามฟังก์ชันที่แอปรองรับ ส่วนผลของผู้เยี่ยมชมมีจุดประสงค์ให้อยู่ในขั้นตอนผู้เยี่ยมชม/เซสชันแทนระเบียนบัญชีทั่วไป SafeSpace ไม่ควรรับประกันว่าจะลบข้อมูลจากทุกสำเนาสำรอง บันทึก แคช หรือระบบทางเทคนิคทันที หากโครงการไม่ได้รับประกันและตรวจสอบเรื่องนั้นจริง"],
  ["27. ความรับผิดชอบของคุณเมื่อใช้แบบประเมิน",
    "คุณมีหน้าที่ตรวจสอบสิ่งที่ส่งก่อนกดส่งแบบประเมิน ไม่ควรส่งข้อมูลของบุคคลอื่นเว้นแต่จำเป็นจริงและคุณมีสิทธิ์ในการแบ่งปันข้อมูลนั้น ห้ามใช้แบบประเมินเพื่อทดสอบระบบในลักษณะที่สร้างความเสียหาย รบกวน แอบอ้างเป็นผู้อื่น หรือจงใจทำให้ระบบเข้าใจผิด การตอบแบบสุ่มหรือจงใจให้ข้อมูลเท็จอาจทำให้ผลลัพธ์มีความหมายลดลง"],
  ["28. ความถูกต้องและปัญหาทางเทคนิค",
    "แบบประเมินอาจได้รับผลกระทบจากข้อผิดพลาดของซอฟต์แวร์ ปัญหาเครือข่าย บริการขัดข้อง การเปลี่ยนชุดคำถาม ความแตกต่างของภาษา หรือปัญหาในการวิเคราะห์อัตโนมัติ ผลลัพธ์อาจได้รับผลกระทบหากคำตอบไม่ครบหรือจงใจให้ข้อมูลไม่ตรงความจริง หากแอปแจ้งข้อผิดพลาด อย่าส่งข้อมูลส่วนตัวที่ละเอียดซ้ำหลายครั้งเพียงเพื่อให้คำขอสำเร็จ ให้ลองใหม่ภายหลังหรือใช้ช่องทางช่วยเหลือที่เหมาะสม"],
  ["29. การเปลี่ยนแปลงของแบบประเมิน",
    "SafeSpace เป็นโครงการโรงเรียนที่อาจพัฒนาต่อเนื่อง คำถาม วิธีให้คะแนนหรือวิเคราะห์ พฤติกรรมของหน้าเว็บ บริการทางเทคนิค มาตรการความปลอดภัย และแนวทางความเป็นส่วนตัวอาจเปลี่ยนแปลง ทำให้เวอร์ชันในอนาคตอาจทำงานแตกต่างจากเวอร์ชันก่อนหน้า จึงแสดงเวอร์ชันนโยบายและวันที่ปรับปรุงล่าสุดเพื่อให้ผู้ใช้ทราบว่ากำลังยอมรับนโยบายฉบับใด"],
  ["30. การยอมรับนโยบาย",
    "ก่อนเริ่มแบบประเมิน คุณต้องมีโอกาสอ่านนโยบายนี้ ปุ่มยอมรับจะถูกปิดไว้จนกว่าคุณจะเลื่อนอ่านถึงท้ายเอกสาร เมื่อเลือก “ยอมรับและดำเนินการต่อ” คุณยืนยันว่าได้มีโอกาสอ่านนโยบาย เข้าใจว่าการทำแบบประเมินเป็นไปโดยสมัครใจ เข้าใจว่าคำตอบอาจถูกประมวลผลด้วยระบบอัตโนมัติหรือ AI เข้าใจว่าผลลัพธ์ไม่ใช่การวินิจฉัย เข้าใจความสำคัญของการไม่ส่งข้อมูลส่วนตัวที่ไม่จำเป็น และเลือกที่จะดำเนินการต่อ หากไม่ยอมรับ คุณสามารถออกจากแบบประเมินโดยไม่เริ่มทำ"],
  ["31. การติดต่อและการแจ้งปัญหา",
    "หากพบปัญหาด้านความเป็นส่วนตัว ความปลอดภัย ความมั่นคงของระบบ การเข้าถึง หรือแบบประเมิน ให้ใช้ช่องทางติดต่อหรือช่วยเหลือที่ SafeSpace มีให้เมื่อมีช่องทางดังกล่าว เมื่อต้องแจ้งปัญหาทางเทคนิค อย่าส่งรหัสผ่านหรือข้อมูลส่วนตัวที่ไม่จำเป็น ควรอธิบายว่าเกิดอะไรขึ้นโดยตัดข้อมูลส่วนตัวออกแทนการส่งคำตอบแบบประเมินทั้งหมด"],
  ["32. ข้อความสำคัญก่อนดำเนินการต่อ",
    "ทำแบบประเมินเมื่อคุณพร้อมและสบายใจ ตอบคำถามตามประสบการณ์ของตัวเอง ให้ข้อมูลเท่าที่จำเป็น และจำไว้ว่าผลจากคอมพิวเตอร์ไม่สามารถเข้าใจคนคนหนึ่งได้ทั้งหมด SafeSpace มีจุดประสงค์เพื่อช่วยให้เกิดการทบทวนและความตระหนัก ไม่ได้มีไว้แทนที่คนที่คุณไว้ใจ การดูแลจากผู้เชี่ยวชาญ หรือบริการฉุกเฉิน"]
];

export const ASSESSMENT_POLICY = ASSESSMENT_POLICY_EN;
